import Head from 'next/head'
import { HomeModule } from '../modules/export'
export default function Home() {
  return (
    <>
      <Head>
        <title>Affliate Marketing</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomeModule />
    </>
  )
}
